// Code generated by mockery v2.53.5. DO NOT EDIT.

package psql

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockPSQLDriver is an autogenerated mock type for the PSQLDriver type
type MockPSQLDriver struct {
	mock.Mock
}

// GetConnConfig provides a mock function with no fields
func (_m *MockPSQLDriver) GetConnConfig() *pgx.ConnConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnConfig")
	}

	var r0 *pgx.ConnConfig
	if rf, ok := ret.Get(0).(func() *pgx.ConnConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgx.ConnConfig)
		}
	}

	return r0
}

// Insert provides a mock function with given fields: ctx, req, args
func (_m *MockPSQLDriver) Insert(ctx context.Context, req string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, req, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertBatch provides a mock function with given fields: ctx, req, args
func (_m *MockPSQLDriver) InsertBatch(ctx context.Context, req string, args []pgx.NamedArgs) error {
	ret := _m.Called(ctx, req, args)

	if len(ret) == 0 {
		panic("no return value specified for InsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []pgx.NamedArgs) error); ok {
		r0 = rf(ctx, req, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectBytes provides a mock function with given fields: ctx, req, args
func (_m *MockPSQLDriver) SelectBytes(ctx context.Context, req string, args ...interface{}) ([]byte, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SelectBytes")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) ([]byte, error)); ok {
		return rf(ctx, req, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) []byte); ok {
		r0 = rf(ctx, req, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, req, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectString provides a mock function with given fields: ctx, req, args
func (_m *MockPSQLDriver) SelectString(ctx context.Context, req string, args ...interface{}) (string, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, req)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SelectString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (string, error)); ok {
		return rf(ctx, req, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) string); ok {
		r0 = rf(ctx, req, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, req, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPSQLDriver creates a new instance of MockPSQLDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPSQLDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPSQLDriver {
	mock := &MockPSQLDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
