// Code generated by mockery v2.53.5. DO NOT EDIT.

package psql

import (
	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// MockPSQLDriver is an autogenerated mock type for the PSQLDriver type
type MockPSQLDriver struct {
	mock.Mock
}

// GetConnConfig provides a mock function with no fields
func (_m *MockPSQLDriver) GetConnConfig() *pgx.ConnConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConnConfig")
	}

	var r0 *pgx.ConnConfig
	if rf, ok := ret.Get(0).(func() *pgx.ConnConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgx.ConnConfig)
		}
	}

	return r0
}

// NewMockPSQLDriver creates a new instance of MockPSQLDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPSQLDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPSQLDriver {
	mock := &MockPSQLDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
