// Code generated by mockery v2.53.5. DO NOT EDIT.

package simple

import (
	iter "iter"

	model "github.com/nk87rus/go-musthave-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockExtStorage is an autogenerated mock type for the ExtStorage type
type MockExtStorage struct {
	mock.Mock
}

// LoadData provides a mock function with given fields: _a0
func (_m *MockExtStorage) LoadData(_a0 interface{}) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveData provides a mock function with given fields: _a0
func (_m *MockExtStorage) SaveData(_a0 iter.Seq[model.StorageRecord]) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SaveData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(iter.Seq[model.StorageRecord]) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockExtStorage creates a new instance of MockExtStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtStorage {
	mock := &MockExtStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
