// Code generated by mockery v2.53.5. DO NOT EDIT.

package handler

import (
	context "context"

	model "github.com/nk87rus/go-musthave-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, sURL, oURL
func (_m *MockStorage) Add(ctx context.Context, sURL string, oURL string) error {
	ret := _m.Called(ctx, sURL, oURL)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, sURL, oURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddBatch provides a mock function with given fields: ctx, data
func (_m *MockStorage) AddBatch(ctx context.Context, data *[]model.StorageRecord) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *[]model.StorageRecord) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, sURL
func (_m *MockStorage) Get(ctx context.Context, sURL string) (string, error) {
	ret := _m.Called(ctx, sURL)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sURL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sURL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersURLs provides a mock function with given fields: ctx
func (_m *MockStorage) GetUsersURLs(ctx context.Context) ([]model.StorageRecord, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersURLs")
	}

	var r0 []model.StorageRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.StorageRecord, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.StorageRecord); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.StorageRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDExists provides a mock function with given fields: ctx, sURL
func (_m *MockStorage) IDExists(ctx context.Context, sURL string) bool {
	ret := _m.Called(ctx, sURL)

	if len(ret) == 0 {
		panic("no return value specified for IDExists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, sURL)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
