// Code generated by generate-reset; DO NOT EDIT.
package handler

func (s *RespBatchItem) Reset() {
	s.ID = ""
	s.SortURL = ""
}
func (s *RespUsersURLs) Reset() {
	s.ShortURL = ""
	s.OrigURL = ""
}
func (s *ReqBatchItem) Reset() {
	s.ID = ""
	s.OrigURL = ""
}
