// Code generated by generate-reset; DO NOT EDIT.
package model

func (s *AuditMsg) Reset() {
	s.Timestamp = 0
	s.Action = ""
	s.UserID = ""
	s.URL = ""
}
func (s *StorageRecord) Reset() {
	s.UUID = ""
	s.ShortURL = ""
	s.OrigURL = ""
	s.UserID = ""
	s.DeletedFlag = false
}
