// Code generated by generate-reset; DO NOT EDIT.
package app

import "github.com/nk87rus/go-musthave-shortener/internal/router/httpsrv"

func (s *App) Reset() {
	if s.httpServer != nil {
		*s.httpServer = *new(httpsrv.Server)
	}
	s.db = nil
}
