// Code generated by mockery v2.53.6. DO NOT EDIT.

package httpsrv

import (
	context "context"

	model "github.com/nk87rus/go-musthave-shortener/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAuditor is an autogenerated mock type for the Auditor type
type MockAuditor struct {
	mock.Mock
}

// Notify provides a mock function with given fields: ctx, data
func (_m *MockAuditor) Notify(ctx context.Context, data model.AuditMsg) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AuditMsg) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockAuditor creates a new instance of MockAuditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditor {
	mock := &MockAuditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
