// Code generated by mockery v2.53.5. DO NOT EDIT.

package httpsrv

import (
	handler "github.com/nk87rus/go-musthave-shortener/internal/handler"
	mock "github.com/stretchr/testify/mock"
)

// MockHandlers is an autogenerated mock type for the Handlers type
type MockHandlers struct {
	mock.Mock
}

// CreateShortURL provides a mock function with given fields: value, repo
func (_m *MockHandlers) CreateShortURL(value string, repo handler.Storage) (string, error) {
	ret := _m.Called(value, repo)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, handler.Storage) (string, error)); ok {
		return rf(value, repo)
	}
	if rf, ok := ret.Get(0).(func(string, handler.Storage) string); ok {
		r0 = rf(value, repo)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, handler.Storage) error); ok {
		r1 = rf(value, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreURL provides a mock function with given fields: id, repo
func (_m *MockHandlers) RestoreURL(id string, repo handler.Storage) (string, error) {
	ret := _m.Called(id, repo)

	if len(ret) == 0 {
		panic("no return value specified for RestoreURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, handler.Storage) (string, error)); ok {
		return rf(id, repo)
	}
	if rf, ok := ret.Get(0).(func(string, handler.Storage) string); ok {
		r0 = rf(id, repo)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, handler.Storage) error); ok {
		r1 = rf(id, repo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockHandlers creates a new instance of MockHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandlers {
	mock := &MockHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
