// Code generated by mockery v2.53.6. DO NOT EDIT.

package httpsrv

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockJWTProcessor is an autogenerated mock type for the JWTProcessor type
type MockJWTProcessor struct {
	mock.Mock
}

// MakeJWT provides a mock function with no fields
func (_m *MockJWTProcessor) MakeJWT() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MakeJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParseJWT provides a mock function with given fields: jwtToken
func (_m *MockJWTProcessor) ParseJWT(jwtToken string) (string, error) {
	ret := _m.Called(jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for ParseJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(jwtToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(jwtToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(jwtToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenExpiration provides a mock function with no fields
func (_m *MockJWTProcessor) TokenExpiration() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TokenExpiration")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// NewMockJWTProcessor creates a new instance of MockJWTProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTProcessor {
	mock := &MockJWTProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
