// Code generated by mockery v2.53.5. DO NOT EDIT.

package memstorage

import (
	context "context"
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nk87rus/go-musthave-shortener/internal/model"
)

// MockExtStorage is an autogenerated mock type for the ExtStorage type
type MockExtStorage struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, id, sURL, oURL
func (_m *MockExtStorage) Add(ctx context.Context, id string, sURL string, oURL string) error {
	ret := _m.Called(ctx, id, sURL, oURL)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, sURL, oURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddBatch provides a mock function with given fields: ctx, data
func (_m *MockExtStorage) AddBatch(ctx context.Context, data iter.Seq[model.StorageRecord]) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, iter.Seq[model.StorageRecord]) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DelURLs provides a mock function with given fields: ctx, uid, urls
func (_m *MockExtStorage) DelURLs(ctx context.Context, uid string, urls []string) error {
	ret := _m.Called(ctx, uid, urls)

	if len(ret) == 0 {
		panic("no return value specified for DelURLs")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, uid, urls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadData provides a mock function with given fields: ctx, rcv
func (_m *MockExtStorage) LoadData(ctx context.Context, rcv interface{}) error {
	ret := _m.Called(ctx, rcv)

	if len(ret) == 0 {
		panic("no return value specified for LoadData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, rcv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockExtStorage creates a new instance of MockExtStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtStorage {
	mock := &MockExtStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
