package processor

import (
	"fmt"
	"go/ast"
	"go/printer"
	"go/token"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var basicTypes = map[string]bool{
	"bool": true, "string": true,
	"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
	"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
	"uintptr": true, "byte": true, "rune": true,
	"float32": true, "float64": true,
	"complex64": true, "complex128": true,
}

func generateResetFile(dir, pkgName string, markedStructs map[string]bool, structures map[string]*ast.StructType, resetMethods map[string]bool) {
	outPath := filepath.Join(dir, "reset.gen.go")
	f, err := os.Create(outPath)
	if err != nil {
		log.Fatalf("failed to create %q: %v", outPath, err)
	}
	defer func() {
		f.Close()
		fmt.Printf("processed package %q, created file %q\n", pkgName, f.Name())
	}()

	fmt.Fprintln(f, "// Code generated by generate-reset; DO NOT EDIT.")
	fmt.Fprintln(f, "package", pkgName)
	fmt.Fprintln(f)

	for structName := range markedStructs {
		st := structures[structName]
		if st == nil {
			log.Printf("warning: marked struct %s not found in structures map", structName)
			continue
		}

		fmt.Fprintf(f, "func (s *%s) Reset() {\n", structName)
		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				fldName := getAnonymousFieldName(field.Type)
				if fldName == "" {
					log.Printf("warning: cannot determine name for anonymous field in %s", structName)
					continue
				}
				generateFieldReset(f, "s", fldName, field.Type, resetMethods)
			} else {
				for _, name := range field.Names {
					generateFieldReset(f, "s", name.Name, field.Type, resetMethods)
				}
			}
		}
		fmt.Fprintln(f, "}")
	}
}

func getAnonymousFieldName(typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return getAnonymousFieldName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	default:
		return ""
	}
}

func generateFieldReset(w io.Writer, baseVar, fieldName string, typ ast.Expr, resetMethods map[string]bool) {
	valueExpr := baseVar + "." + fieldName
	handleValue(w, valueExpr, typ, resetMethods)
}

// handleValue - генерирует код для сброса значения
func handleValue(w io.Writer, valueExpr string, typ ast.Expr, resetMethods map[string]bool) {
	switch t := typ.(type) {
	case *ast.Ident:
		name := t.Name
		if isBasicType(name) {
			fmt.Fprintf(w, "\t%s = %s\n", valueExpr, zeroValue(typ))
		} else {
			if resetMethods[name] {
				fmt.Fprintf(w, "%s.Reset()\n", valueExpr)
			} else {
				// fmt.Fprintf(w, "\t%s = *new(%s)\n", valueExpr, name)
				fmt.Fprintf(w, "\t%s = nil\n", valueExpr)
			}
		}

	case *ast.StarExpr:
		// указатель: если не nil, выполняем сброс
		fmt.Fprintf(w, "if %s != nil {\n", valueExpr)
		handleValue(w, "*"+valueExpr, t.X, resetMethods)
		fmt.Fprintf(w, "}\n")

	case *ast.ArrayType:
		if t.Len == nil {
			// слайс
			fmt.Fprintf(w, "\t%s = %s[:0]\n", valueExpr, valueExpr)
		} else {
			// массив
			var buf strings.Builder
			if err := formatNode(&buf, t); err != nil {
				log.Printf("failed to format array type: %v", err)
				return
			}
			fmt.Fprintf(w, "\t%s = %s{}\n", valueExpr, buf.String())
		}

	case *ast.MapType:
		fmt.Fprintf(w, "clear(%s)\n", valueExpr)

	case *ast.StructType:
		// анонимная структура
		var buf strings.Builder
		if err := formatNode(&buf, t); err != nil {
			log.Printf("failed to format struct type: %v", err)
			return
		}
		fmt.Fprintf(w, "\t%s = %s{}\n", valueExpr, buf.String())

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		fmt.Fprintf(w, "\t%s = nil\n", valueExpr)

	default:
		var buf strings.Builder
		if err := formatNode(&buf, typ); err != nil {
			log.Printf("failed to format type: %v", err)
			return
		}
		fmt.Fprintf(w, "\t%s = *new(%s)\n", valueExpr, buf.String())
	}
}

// isBasicType - проверяет является ли указанный тип базовым
func isBasicType(name string) bool {
	return basicTypes[name]
}

// zeroValue - возвращает начальное значение в соответсвии с типом
func zeroValue(field ast.Expr) string {
	if ident, ok := field.(*ast.Ident); ok {
		switch ident.Name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"uintptr", "byte", "rune", "float32", "float64",
			"complex64", "complex128":
			return "0"
		case "bool":
			return "false"
		case "string":
			return `""`
		}
	}
	return "nil"
}

// formatNode - конвертирует ast.Node в строку
func formatNode(buf *strings.Builder, node ast.Node) error {
	fset := token.NewFileSet()
	return (&printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}).Fprint(buf, fset, node)
}
